language: node_js
node:
    - 12

before_install: npm i lerna
install: npm run boot

jobs:
    include:
        - stage: Test
          name: Frontend
          install: skip
          script: lerna run --scope time-manager-frontend test

        - stage: Build
          name: Backend
          install: skip
          script: lerna run --scope time-manager-api build

        - stage: Build
          name: Frontend
          install: skip
          script: lerna run --scope time-manager-frontend build
