language: node_js
node:
    - 12

install:
    - npm i lerna
    - npm run boot

script:
    - lerna run --scope time-manager-api test
    - lerna run --scope time-manager-frontend test
    - lerna run --scope time-manager-api build
    - lerna run --scope time-manager-frontend build
